# Generated by Django 4.0.5 on 2022-06-30 17:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraccount',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AddField(
            model_name='userdetail',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='date registered'),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='date_registered',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date registered'),
            preserve_default=False,
        ),
    ]
