# Generated by Django 4.0.4 on 2022-05-24 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='height',
            field=models.CharField(blank=True, choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default='5 feet', max_length=10),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/image'),
        ),
    ]
