# Generated by Django 4.0.4 on 2022-06-14 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='cause_of_death',
            field=models.TextField(blank=True, null=True),
        ),
    ]
