# Generated by Django 4.0.4 on 2022-05-24 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_userdetail_height_alter_userdetail_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='school_type',
            field=models.CharField(choices=[('E', 'Elementary'), ('S', 'Secondary'), ('T', 'Tertiary'), ('P', 'Post Grad')], max_length=15),
        ),
    ]
