# Generated by Django 4.0.5 on 2022-07-01 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_useraccount_options_userdetail_date_modified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oldestalive',
            name='current',
        ),
    ]
