# Generated by Django 4.0.5 on 2022-08-22 18:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_useraccount_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2022, 8, 22, 18, 8, 39, 833005, tzinfo=utc), verbose_name='Date of birth'),
        ),
    ]
