# Generated by Django 4.0.4 on 2022-06-14 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_userdetail_cause_of_death'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdetail',
            options={'verbose_name': 'user account', 'verbose_name_plural': 'user accounts'},
        ),
    ]
