# Generated by Django 4.0.5 on 2022-08-25 15:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_useraccount_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='biography',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2022, 8, 25, 15, 14, 21, 200886, tzinfo=utc), verbose_name='Date of birth'),
        ),
    ]
