# Generated by Django 4.1.2 on 2022-10-29 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_useraccount_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='school_level',
            field=models.CharField(choices=[('Elementary', 'Elementary'), ('Secondary', 'Secondary'), ('Tertiary', 'Tertiary'), ('Post_Graduation', 'Post Graduation')], max_length=15),
        ),
    ]
