# Generated by Django 4.0.4 on 2022-06-14 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_userdetail_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraccount',
            options={'verbose_name': 'user account', 'verbose_name_plural': 'user accounts'},
        ),
        migrations.AlterModelOptions(
            name='userdetail',
            options={},
        ),
    ]
