# Generated by Django 4.0.5 on 2022-07-01 15:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_additionalemail_date_modified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='occupation',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='date registered'),
        ),
        migrations.AddField(
            model_name='occupation',
            name='date_registered',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date registered'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='occupation',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
