# Generated by Django 4.0.4 on 2022-06-16 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_useraccount_options_alter_userdetail_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='school_level',
            field=models.CharField(choices=[('E', 'Elementary'), ('S', 'Secondary'), ('T', 'Tertiary'), ('P', 'Post Graduation')], max_length=15),
        ),
    ]
