# Generated by Django 4.0.5 on 2022-08-25 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_useraccount_biography_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='biography',
            field=models.TextField(blank=True, default='I am the next big thing'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='cause_of_death',
            field=models.TextField(blank=True, default='i am not dead'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='date_of_birth',
            field=models.DateField(blank=True, verbose_name='Date of birth'),
        ),
    ]
