# Generated by Django 4.0.5 on 2022-07-01 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_occupation_date_modified_occupation_date_registered_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geneticdisease',
            name='type',
            field=models.CharField(choices=[('H', 'Hereditary'), ('A', 'Acquired')], max_length=11),
        ),
    ]
