# Generated by Django 4.1.2 on 2022-10-31 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_geneticdisease_age_of_infection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='name_of_school',
            field=models.TextField(verbose_name='Name of school'),
        ),
    ]
