# Generated by Django 4.0.5 on 2022-06-25 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_userdetail_dad_alter_education_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='mum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mother', to='account.userdetail'),
        ),
        migrations.AlterField(
            model_name='oldestalive',
            name='elected',
            field=models.DateField(auto_now_add=True, verbose_name='Date Elected'),
        ),
    ]
