# Generated by Django 4.1.2 on 2022-11-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_education_name_of_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geneticdisease',
            name='type',
            field=models.CharField(choices=[('Hereditary', 'Hereditary'), ('Hereditary', 'Acquired')], max_length=11),
        ),
    ]
