# Generated by Django 4.1.2 on 2022-11-08 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_geneticdisease_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['year_of_entrance'], 'verbose_name_plural': 'Education'},
        ),
    ]
