# Generated by Django 4.1.3 on 2022-12-01 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_education_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
