# Generated by Django 4.0.5 on 2022-07-11 10:42

import datetime
from django.db import migrations, models
import django.db.models.manager
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='image',
            managers=[
                ('public', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(default=datetime.datetime(2022, 7, 11, 10, 42, 36, 145514, tzinfo=utc), max_length=300),
        ),
    ]
