# Generated by Django 4.0.5 on 2022-09-01 07:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(default=datetime.datetime(2022, 9, 1, 7, 11, 15, 869355, tzinfo=utc), max_length=300),
        ),
    ]
