# Generated by Django 4.1.3 on 2022-12-01 12:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_alter_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(default=datetime.datetime(2022, 12, 1, 12, 17, 21, 437933, tzinfo=datetime.timezone.utc), max_length=300, primary_key=True, serialize=False),
        ),
    ]
