# Generated by Django 4.1.3 on 2022-12-01 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0004_alter_image_name'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='image',
            managers=[
            ],
        ),
    ]
