# Generated by Django 4.1.3 on 2022-12-01 13:59

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0005_alter_image_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='image',
            managers=[
                ('public', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='image',
            name='is_public',
            field=models.BooleanField(choices=[('True', 'True'), ('False', 'False')], default=True),
        ),
    ]
