# Generated by Django 4.1.3 on 2022-12-20 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0011_alter_image_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=models.ImageField(upload_to='photos/2022-12-20/'),
        ),
    ]
