# Generated by Django 4.1.3 on 2022-12-20 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0013_alter_image_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='is_public',
            field=models.BooleanField(default=1),
        ),
    ]
