# Generated by Django 4.1.3 on 2023-03-06 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0020_alter_image_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=models.ImageField(upload_to='images/2023-3-6/'),
        ),
    ]
