# Generated by Django 4.1.3 on 2022-12-01 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_alter_video_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='name',
            field=models.CharField(max_length=300, primary_key=True, serialize=False),
        ),
    ]
