# Generated by Django 4.0.5 on 2022-10-10 16:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_alter_video_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='name',
            field=models.CharField(default=datetime.datetime(2022, 10, 10, 16, 52, 2, 830730, tzinfo=utc), max_length=300),
        ),
    ]
