# Generated by Django 4.2.6 on 2023-10-28 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_alter_video_movie_shot_alter_video_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='movie_shot',
            field=models.ImageField(blank=True, upload_to='videoShots/2023-10-28/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(max_length=250, upload_to='videos/2023-10-28/'),
        ),
    ]
