# Generated by Django 4.1.3 on 2022-12-01 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_alter_video_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='is_public',
            field=models.BooleanField(choices=[('True', 'True'), ('False', 'False')], default=True),
        ),
    ]
