# Generated by Django 4.1.3 on 2022-12-20 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0009_alter_video_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='is_public',
            field=models.BooleanField(),
        ),
    ]
