# Generated by Django 4.1.3 on 2022-12-20 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0010_alter_video_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='is_public',
            field=models.BooleanField(default=1),
        ),
    ]
