# Generated by Django 4.1.3 on 2023-03-06 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0016_alter_video_movie_shot_alter_video_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='movie_shot',
            field=models.ImageField(blank=True, upload_to='video_shots/2023-3-6/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(max_length=250, upload_to='videos/2023-3-6/'),
        ),
    ]
